Version 2.5.8
        - Improved: CliNamer to support a parent CliNamer. Unique names were only checked within the command builder
          so the current command was not aware of names of sibling commands. This is now fixed.
          And from now on, we will throw an explanatory exception when there is a name or alias conflict like this:
          ```console
          System.Exception: CommandAlias 'c' for 'createschema' conflicts with parent CommandAlias for 'checkfornewtools'!
          ```
          This is because System.CommandLine threw a vague exception when there was a conflict during parsing:
          ```console
          System.ArgumentException: An item with the same key has already been added. Key: c
          ```
          Unique names are checked for DirectiveName (surrounded with []), CommandName, CommandAlias, OptionName, OptionAlias.
          Auto short form aliases will be always derived from symbol name even when a specific name was specified,
          because if user specifies a specific name with all lowercase like `checkfornewtools`, we cannot split word boundaries.
          Help output will show short aliases first consistently especially for commands (order by prefix and then by length).

        - Improved: Set the values for the parent command accessors before directive, option and argument properties so that
          property get accessors can access them:
          ```c#
          public class DefaultSettingsCliCommand
          {
              [CliOption]
              public string SettingsFile => RootCommand.SettingsFile; // <-- Avoid Error Here

              public RootCliCommand RootCommand { get; set; }
          }
          ```

        - Fixed: Usage of `[CliArgument].AllowedValues` caused compiler error CS1061 because `Argument<T>.AcceptOnlyFromAmong(...)`
          was moved to extension method `System.CommandLine.ArgumentValidation.AcceptOnlyFromAmong(...)` in latest System.CommandLine.